settings={
	'office':{
		'url':'############',
		'account':'############',
	    'password':'############'
	},
	'gloryskyM':{
		'url':'############',
		'account':'############',
	    'password':'############'
	},
	'gloryskyW':{
		'url':'############',
		'account':'############',
	    'password':'############'
	},
	'psdemoM':{
		'url':'############',
		'account':'############',
	    'password':'############'
	},
	'psdemoW':{
		'url':'############',
		'account':'############',
	    'password':'############'
	}
}

